### ISSUE TITLE
vscode插件无法使用adb连接手机

### ISSUE THREAD

**Issue by epicDove** [hyb1996/AutoJs-Docs#36]
使用局域网可以连接到设备上，但是使用adb方式不行，可以搜索到设备列表，但是点击连接后插件报错：
[[object Object]]Cannot read property 'toString' of null
TypeError: Cannot read property 'toString' of null
	at y.<anonymous> (c:\Users\zx007\.vscode\extensions\hyb1996.auto-js-pro-ext-1.0.1\dist\extension.js:51:37265)
	at Generator.next (<anonymous>)
	at s (c:\Users\zx007\.vscode\extensions\hyb1996.auto-js-pro-ext-1.0.1\dist\extension.js:51:34436)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
![image](https://user-images.githubusercontent.com/13879520/88367974-9de99500-cdbf-11ea-9c20-df8085c99f52.png)

**Comment by hyb1996** [comment]
啥版本的客户端呢

**Comment by epicDove** [comment]
Pro 8.0.0-5.apk与7.0.4-1都试过
vscode版本：1.47.3
插件版本：Auto.js-Pro-Ext v1.0.1与1.0.0

**Comment by hyb1996** [comment]
试试 Pro 8.2.0

**Comment by epicDove** [comment]
刚试了Pro 8.2.0，一样样的报错
