### ISSUE TITLE
调用 images 的recycle() 报错

### ISSUE THREAD

**Issue by Shanxian** [hyb1996/AutoJs-Docs#49]
```
app 版本号 4.1.1
var phoneImageFilePath = '/sdcard/JSimages/';
var screenImagePath = phoneImageFilePath + 'screen.jpg';

var img1 = images.read(screenImagePath);
var img2 = images.read(phoneImageFilePath + 'complete.jpg');
var compareResult = findImage(img1, img2, {
            threshold: 0.5
        });
img1.recycle();  

log:
10:23:37.448/E: org.mozilla.javascript.WrappedException: Wrapped com.stardust.util.ResourceMonitor$UnclosedResourceException: id = 20, resource = Mat [ 79*215*CV_8UC4, isCont=true, isSubmat=false, nativeObj=0xffffffffc00e9f08, dataAddr=0xffffffffbc7d4000 ] (file:///android_asset/modules/__images__.js#412)

com.stardust.util.ResourceMonitor$UnclosedResourceDetectedException: org.mozilla.javascript.WrappedException: Wrapped com.stardust.util.ResourceMonitor$UnclosedResourceException: id = 20, resource = Mat [ 79*215*CV_8UC4, isCont=true, isSubmat=false, nativeObj=0xffffffffc00e9f08, dataAddr=0xffffffffbc7d4000 ] (file:///android_asset/modules/__images__.js#412)
 at com.stardust.util.ResourceMonitor$1.run(ResourceMonitor.java:77)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:230)
 at android.app.ActivityThread.main(ActivityThread.java:7763)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:508)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: org.mozilla.javascript.WrappedException: Wrapped com.stardust.util.ResourceMonitor$UnclosedResourceException: id = 20, resource = Mat [ 79*215*CV_8UC4, isCont=true, isSubmat=false, nativeObj=0xffffffffc00e9f08, dataAddr=0xffffffffbc7d4000 ] (file:///android_asset/modules/__images__.js#412)
 at com.stardust.autojs.AutoJs.lambda$init$0(AutoJs.java:95)
 at com.stardust.autojs.-$$Lambda$AutoJs$3XHfVdQAd51bDAupzUg8b79-jFk.create(Unknown Source:0)
 at com.stardust.util.ResourceMonitor.onOpen(ResourceMonitor.java:46)
 at com.stardust.autojs.core.opencv.Mat.<init>(Mat.java:43)
 at com.stardust.autojs.core.image.TemplateMatching.getPyramidDownAtLevel(TemplateMatching.java:152)
 at com.stardust.autojs.core.image.TemplateMatching.fastTemplateMatching(TemplateMatching.java:88)
 at com.stardust.autojs.core.image.TemplateMatching.fastTemplateMatching(TemplateMatching.java:55)
 at com.stardust.autojs.runtime.api.Images.findImage(Images.java:294)
 at java.lang.reflect.Method.invoke(Native Method)
 at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
 at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
 at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1479)
 at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
 at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
 at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399)
 at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3452)
 at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
 at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.kt:76)
 at com.stardust.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:20)
 at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:21)
 at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0(LoopBasedJavaScriptEngine.java:46)
 at com.stardust.autojs.engine.-$$Lambda$LoopBasedJavaScriptEngine$ffoqWCRm35mszUY9lWNMZL1Mntg.run(Unknown Source:6)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:230)
 at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:65)
 at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:38)
 at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(LoopedBasedJavaScriptExecution.java:42)
 at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:43)
 at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:37)
 at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:31)
 at java.lang.Thread.run(Thread.java:919)
Caused by: com.stardust.util.ResourceMonitor$UnclosedResourceException: id = 20, resource = Mat [ 79*215*CV_8UC4, isCont=true, isSubmat=false, nativeObj=0xffffffffc00e9f08, dataAddr=0xffffffffbc7d4000 ]
 at com.stardust.autojs.AutoJs.lambda$init$0(AutoJs.java:91)
 ... 31 more
```
求告知，怎么解决

**Comment by hyb1996** [comment]
免费版内存泄露。Pro已修复
